### ISSUE TITLE
cadasta-api npm dependencies not being reinstalled

### ISSUE THREAD

**Issue by bjohare** [Cadasta/aws-deployment#2]
When doing a redeployment of the platform, cadasta-api npm dependencies are not getting reinstalled. Any changes to (for example) the cadasta-provider-ona dependency are not being picked up.

**Comment by ian-ross** [comment]
OK, I know what this is.  I fixed a couple of other instances of it, but I must have missed this one.  I'll deal with it later today.

**Comment by bjohare** [comment]
Just submitted a PR for this...

**Comment by ian-ross** [comment]
OK, that looks good.  Merged, and I'll close this.  I fixed one other place where the force flag should probably be used with NPM.  For reference, I found that a recent update of something stopped the Ansible `npm` module from working, which is why I switched over to running `npm` directly.
